### PR TITLE
Add env file example & more database config

### PR DESCRIPTION
**Pull request by deathart**

### CODE REVIEW

**Comment by VictoriqueMoe** [comment]
wut?

**Comment by deathart** [comment]
Hello,

To make it easier to configure the bot, the best of all is to use dotenv with .env files

And the pull request allows to use other type of bdd

Being an open project I allowed myself this pull request if it suits you I will make other pull request :)

**Comment by VictoriqueMoe** [comment]
I appreciate the efforts, but this bot is NOT ready for being used out side of my deployment. this bot requires at least 4 additional micro-services written in Java that are currently deployed under a Kubernetes cluster.

The front end is not finished yet and some commands are bespoke to myself, the env you uploaded is not complete

**Comment by deathart** [comment]
Ok thanks to you I will reopen it when the time comes :)

**Comment by VictoriqueMoe** [comment]
out of interest, how did you find this? 

Please see my code comments, you are welcome to raise PR, but i do not accept `any` unless really have to, and i follow a strict OOP model using DI and not a functional one.

I should write a "How to raise a PR", as being a software architect, i have strict coding styles :D

**Comment by deathart** [comment]
Found what?

For your coding styles I respect but I strongly advise you to update your eslint configurations :)

**Comment by VictoriqueMoe** [comment]
> Found what?
> 
> For your coding styles I respect but I strongly advise you to update your eslint configurations :)

How did you find this project, I never really expected anyone to really care much.

Yes, ESlint config is on the list to do. right after i migrate the category engine

**Comment by deathart** [comment]
You are on the readme of this depot: https://github.com/oceanroleplay/discord.ts

**Comment by VictoriqueMoe** [comment]
> You are on the readme of this depot: https://github.com/oceanroleplay/discord.ts

Oh right, yea, i am a co-owner of that project. 

Well, seeing as no one has ever wanted to help me with this bot, maybe i can finally get someone, because this codebase is really huge and hard for a single person to maintain, it's almost the size of a lot of enterprise apps right now

**Comment by deathart** [comment]
Oh right, if I can help, it will be with great pleasure

**Comment by VictoriqueMoe** [comment]
> Oh right, if I can help, it will be with great pleasure

THANK YOU!

Add me on discord: `Victorique#0001` 

I am making a new PR now for props, i will add you as a reviewer! <3 i know this bot will be the best. i already have a front end and AI stuff written in Java, it's fully replaced all Dyno functions but better!

**Comment by deathart** [comment]
Your discord does not allow friend requests :( add me `deathart#0941`

**Comment by deathart** [comment]
I look forward to helping you

**Pull request closed without merging**
